### ISSUE TITLE
Update No. of downloaded pics after online update

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/RedittyWalls#3]

**Comment by guyett92** [comment]
Hi,

I'd like to give this one a shot!

**Comment by Abdur-rahmaanJ** [comment]
Yare are assigned. Thanks 🎉

**Comment by SUBHAMILA** [comment]
can i try this?

**Comment by sandipan-basak** [comment]
Hi, I am new to open source, and I see that there is no resolution yet. Can I work on this if no one else is currently working on this?
